# WEB配置
server:
  port: 8080
  servlet:
    context-path: /spring

# DB配置
spring:
  mvc:
    throw-exception-if-no-handler-found: true # 出现错误时, 直接抛出异常
  web:
    resources:
      add-mappings: false # 工程资源文件不建立映射
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      filters: stat
#  redis:
#    host: localhost
#    port: 6379
#    password: password
#    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml


# 配置文件加密
# 执行对配置文件中的DEC（文本）数据进行加密并自动生成ENC（密文）（执行的密码要与jasypt.encryptor.password一致）
# 加密命令：
#  1. mvn jasypt:encrypt -Djasypt.encryptor.password=111111
#  2. mvn jasypt:encrypt -Djasypt.plugin.path=file:src/main/resources/application.yml -Djasypt.encryptor.password=111111
# 加密后，使用ENC（）由系统自动解密（单独执行的解密命令：mvn jasypt:decrypt -Djasypt.encryptor.password=111111）
jasypt:
  encryptor:
    password: 111111

password:
  test1: 123456
  test2: ENC(Fz+8SzH5kF6PYW254QDnXKewJ0TY2ei5QGsPYseWT0m9YDWr01dut9S+aqj/rAXE)